### ISSUE TITLE
Opening a window to a new tab in competencies.us logs the user out in the new tab

### ISSUE THREAD

**Issue by eddavies** [cassproject/competencies.us#10]
![opening a new tab competecies us](https://user-images.githubusercontent.com/23706850/31901807-6f408494-b7d7-11e7-9b95-bf17217e28b2.PNG)
![the new tab logged out](https://user-images.githubusercontent.com/23706850/31901812-7137564c-b7d7-11e7-8f43-a92055be9cdf.PNG)

**Comment by Lomilar** [comment]
See #15.
