### ISSUE TITLE
Top toolbar dropdown does not work if browser window is shrunk

### ISSUE THREAD

**Issue by eddavies** [cassproject/competencies.us#12]
![window smaller can no longer drop down](https://user-images.githubusercontent.com/23706850/31903390-cdddb486-b7dc-11e7-9975-71dec20e5643.PNG)
Moving your cursor onto debug, file, workspace, etc. does not open their respective dropdown menus when the browser window is resized smaller.

**Comment by Lomilar** [comment]
Clicking the debug, file, etc opens the dropdown, as it is in 'touch' mode. Unless I am mis-reproing it.

**Comment by eddavies** [comment]
I see, just the hover drop down does not work, clicking the titles works (did not know this was intentional)
