### ISSUE TITLE
Window resizing negatively affects popout windows

### ISSUE THREAD

**Issue by eddavies** [cassproject/competencies.us#13]
![popout window after resizing](https://user-images.githubusercontent.com/23706850/31903752-f3f5ee1c-b7dd-11e7-8932-8e8db3194450.PNG)
This occurred after opening a popout window in a maximized window and then shrinking the window.

**Comment by Lomilar** [comment]
Fixed in 2d5af58c7020364b16fd99b9794f31898d362511

**Comment by eddavies** [comment]
fix verified
