### ISSUE TITLE
Stay logged in.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/competencies.us#15]
Should stay logged in over page refreshes and any other nonsense, except server switching.

**Comment by Lomilar** [comment]
Doesn't remember which identity I have selected.

**Comment by eddavies** [comment]
I'm still logged out after refreshing

**Comment by eddavies** [comment]
Refreshing the page while editing identity settings (the gear in the top right) brings up a relog popout when it shouldn't since it doesn't actually log the user out.

**Comment by Lomilar** [comment]
OK to test.

**Comment by eddavies** [comment]
fix verified
