### ISSUE TITLE
Cannot create assertions about one's self.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/competencies.us#2]
Assertion targets are only contacts, not identities at the moment.

**Comment by Lomilar** [comment]
Seems to have been fixed at some point.

**Comment by eddavies** [comment]
Agents are all generated identities for the logged in user. Subjects include all owned identities as well as contacts. So seems to be working as intended.

On another note, would "agent" and "subject" be confusing to most users?

Still testing to see if any related issues popup.

**Comment by Lomilar** [comment]
Not if they have read the documentation, however, that assertion creator is the expert view.

Adding @kchavas.

**Comment by kchavas** [comment]
The whole contacts and identities portion might be confusing to new users (and anyone who has not read the documentation) but it sounds like this is working as intended now. A user can create an assertion about himself by asserting about one of his own identities, correct? Am I missing something?

**Comment by Lomilar** [comment]
Nope. You're right on. Terminology may be confusing for non-manual readers.

**Comment by Lomilar** [comment]
@kchavas OK to close?

**Comment by kchavas** [comment]
yes please close
