### ISSUE TITLE
Remove URL parameters from URL bar so Google can OAuth.

### ISSUE THREAD

**Issue by eddavies** [cassproject/competencies.us#6]
![cannot log in globally with google](https://user-images.githubusercontent.com/23706850/31629779-847839d8-b269-11e7-8c88-83634664366a.PNG)

Originally was working without error. Not sure how to reproduce yet, but as of now I am unable to log in Globally with google while using Chrome. However this began occurring after I signed in on Firefox using the same account. Currently, Google Sign in works on firefox for me, but not on Chrome. 

Still investigating

**Comment by Lomilar** [comment]
After parameters are parsed, ? should be removed from URL bar.

**Comment by Lomilar** [comment]
Fixed along with #3

**Comment by eddavies** [comment]
Not running into this issue anymore.
