### ISSUE TITLE
Changing an identity name in the identity settings screen is awkward (minor)

### ISSUE THREAD

**Issue by eddavies** [cassproject/competencies.us#8]
The fact that clicking sends the user off being able to type is awkward. The cursor begins at the beginning of the identity's name forcing the use of arrow keys. Clicking enter creates a new paragraph when it should complete the action (shift-enter to make a new paragraph is more intuitive).

Screenshot of where I'm referring to:
![identity management screen](https://user-images.githubusercontent.com/23706850/31731361-a4b9cdc0-b3e9-11e7-8b10-712ab9567282.PNG)

**Comment by Lomilar** [comment]
Also always selects the last name to edit.

**Comment by Lomilar** [comment]
Ok to test.

**Comment by eddavies** [comment]
Much better than before. Not having to use the arrow keys to get to the end of the text is nice. There is no way to drop down a line/start a new paragraph anymore which I don't see any reason why someone would need to in the first place.
