### ISSUE TITLE
Unable to copy contact invitation error message popping up unintentionally (minor)

### ISSUE THREAD

**Issue by eddavies** [cassproject/competencies.us#9]
Clicking on "generate" when attempting to generate a contact invitation always gives an error "unable to copy to clipboard" which may be confusing to the user since clicking copy correctly copies the invitation. Either the invitation should be copied automatically or the error message should not pop up.

The error message should only pop up if the user clicked on copy and the invitation was not copied, unless this is designed to auto copy.

![unable to copy to clipboard](https://user-images.githubusercontent.com/23706850/31732086-13f4d6a6-b3ec-11e7-856a-7d51c04c8285.PNG)

**Comment by Lomilar** [comment]
Which browser?
Cannot repro.

**Comment by eddavies** [comment]
This is no longer occurring and I can no longer reproduce.
